# Generated by Django 4.2.1 on 2023-05-29 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Barang',
        ),
    ]
