# Generated by Django 4.2.1 on 2023-06-02 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_orderplaced_status_wishlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Wishlist',
        ),
    ]
